version: '3.1'

services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity-server-datadir:C:/ProgramData/JetBrains/TeamCity
      - teamcity-server-log:C:/TeamCity/logs
    ports:
      - "8111:8111"

  teamcity-agent:
    image: jetbrains/teamcity-agent
    volumes: 
      - teamcity-agent-conf:C:/BuildAgent/conf
    environment:
        SERVER_URL: http://teamcity:8111

volumes:
  teamcity-server-datadir:
  teamcity-server-log:
  teamcity-agent-conf:

