version : '3.7'

services:
  generator:
    image: deepakorantak/generator-api:9
    ports: 
      - "8080:80"

  mail:
    image: deepakorantak/mailhog:win
    ports:
      - "4080:80"
      - "1025:25"
  
  integration:
    image: deepakorantak/gen-api-itest:9
    build: .

      
